"""add token_version to users

Revision ID: 36189298db33
Revises: 0001
Create Date: 2026-04-17 11:11:44.689859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36189298db33'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
