"""add FK indexes

Revision ID: 5216a5103025
Revises: 1ef48e576e45
Create Date: 2026-04-16 19:03:23.423057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5216a5103025'
down_revision: Union[str, Sequence[str], None] = '1ef48e576e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_vendor_id'), 'bookings', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_services_vendor_id'), 'services', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_availability_vendor_id'), 'vendor_availability', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendors_user_id'), 'vendors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_user_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendor_availability_vendor_id'), table_name='vendor_availability')
    op.drop_index(op.f('ix_services_vendor_id'), table_name='services')
    op.drop_index(op.f('ix_bookings_vendor_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    # ### end Alembic commands ###
