"""add stripe payment and webhook columns

Revision ID: e0b51adea996
Revises: a38a7b557303
Create Date: 2026-04-16 19:54:15.410274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b51adea996'
down_revision: Union[str, Sequence[str], None] = 'a38a7b557303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(length=50), nullable=False, server_default='unpaid'))
    op.add_column('bookings', sa.Column('amount_cents', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('platform_fee_cents', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('currency', sa.String(length=10), nullable=False, server_default='usd'))
    op.add_column('bookings', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('customer_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('vendor_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('funds_released_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bookings_payment_intent_id'), 'bookings', ['payment_intent_id'], unique=False)
    op.add_column('vendors', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    op.add_column('vendors', sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'stripe_onboarding_complete')
    op.drop_column('vendors', 'stripe_account_id')
    op.drop_index(op.f('ix_bookings_payment_intent_id'), table_name='bookings')
    op.drop_column('bookings', 'funds_released_at')
    op.drop_column('bookings', 'vendor_confirmed_at')
    op.drop_column('bookings', 'customer_confirmed_at')
    op.drop_column('bookings', 'paid_at')
    op.drop_column('bookings', 'confirmed_at')
    op.drop_column('bookings', 'currency')
    op.drop_column('bookings', 'platform_fee_cents')
    op.drop_column('bookings', 'amount_cents')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'payment_intent_id')
    # ### end Alembic commands ###
